version: "3.8"

# define volume for Postgres database and artifact store
volumes:
  postgres_data:
  artifact_store:

# define services
# one for Pstgres database
# one for tracking server
services:
  mlflow-db:
    container_name: mlflow-backend-store
    image: postgres:13.3
    env_file:
      - .envs/.postgres

  mlflow-server:
    image: local-mlflow-tracking-server
    container_name: local-mlflow-tracking-server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        MLFLOW_ARTIFACT_STORE: ${MLFLOW_ARTIFACT_STORE}
    ports: 
      - ${LOCAL_DEV_MLFLOW_SERVER_PORT}:${LOCAL_DEV_MLFLOW_SERVER_PORT}
    depends_on:
      - mlflow-db
    env_file:
      - .envs/.postgres
      - .envs/.mlflow-common # to keep the common environment variables used by both local and remote tracking servers
      - .envs/.mlflow-dev # hold environment variables specific to development mlflow instance (local installation)
    volumes:
      - ./:/app
      - artifact_store:${MLFLOW_ARTIFACT_STORE}
    ipc: host
    init: true